### ISSUE TITLE
Animated Tag rotation behaving unexpectedly

### ISSUE THREAD

**Issue by mynkijames** [neumond/blender-md3#14]
Hi, 

I've been working through all the steps of creating an animated Quake 3 character and have had great results with this exporter after some trial and error. I have my head, upper and lower .md3 meshes lined up properly and animating in-game and they look almost perfect-- that is, until an animated Tag plays a rotation (such as raising and turning a weapon during a taunt animation, a back-flip jump animation or any of the full-body death animations). Although oriented correctly when facing forward, the model attached to my Tag seems to move the opposite direction it was animated in Blender (for example tag_head turning left around the Y-axis in Blender will make the attached head mesh turn right in-game, or if tag_head is animated tilting back, the head will tilt forward in-game).

I've tried comparing my results to Quake 3's own .md3 characters which I've brought into Blender with the importer, and I'm confused by the results. The Tags on these imported .md3s are initially lined up the way mine are, but they counter-rotate unintuitively rather than the way you'd expect during any turning movements. This makes me wonder if Tags' rotations are being imported and exported somehow inverted... or am I just missing something obvious? I'm totally stumped :) Hoping you have some insight, and thanks very much for your time and effort!

**Comment by neumond** [comment]
Hi, this seems to be related to #6 and should be fixed long ago. I've added test to ensure export-import roundtrip doesn't break anything in tag animations and tried to import one of the original models, everythings seems to be fine.

Try this addon version (basically most fresh snapshot of master):
[blender_md3.zip](https://github.com/neumond/blender-md3/files/1964520/blender_md3.zip)

**Comment by mynkijames** [comment]
I don't know how I managed it but I was indeed using an old version of the exporter. With the new version you sent I re-exported my models and everything works perfectly. I'm excited to tackle more character projects soon! Thanks again for helping me with my foolish mistakes :)
