### ISSUE TITLE
Vertex Alpha (used by alphaGen Vertex)

### ISSUE THREAD

**Issue by KillPixelGames** [neumond/blender-md3#22]
Hi, does this exporter also export the vertex alpha values?  Something I'm working on relies on 'alphaGen Vertex' (quake3 shader parm) but I'm unable to get it working.

**Comment by zturtleman** [comment]
MD3 models do not contain vertex color/alpha.

`alphaGen vertex` should only be used in Quake 3 shaders for map surfaces (.bsp) and 2D menu/hud. In Quake 3 MD3 shader vertex color/alpha is unpredictable as it's from a previously drawn map surface or 2D.

If you bake an MD3 into a Quake 3 .bsp using a misc_model entity, there will be vertex color/alpha so `alphaGen vertex` is valid to use. q3map2 supports [`q3map_alphaGen` and `q3map_alphaMod`](http://q3map2.robotrenegade.com/docs/shader_manual/q3map-global-directives.html) for controlling the vertex alpha (example in [Simon O'Callaghan's terrain blending tutorial](http://www.simonoc.com/pages/articles/terrain2_1.htm)). (Though I haven't tested controlling vertex alpha with misc_model entities.)

**Comment by KillPixelGames** [comment]
I was afraid of that.  I'm using Darkplaces, which only supports a single q3 shader stage, I was hoping this could be a hacky way to get around that and achieve some nice alpha fades on scrolling textures such as smoke/fog.

I've done some tests baking an .ase misc_model but it's pretty inflexible and limited.

Thanks for the info!
