### ISSUE TITLE
Not running in 2.78

### ISSUE THREAD

**Issue by Pande** [neumond/blender-md3#4]
Tested both by normal install, manual install, and by running the script from text editor. Something has broken. :/

**Comment by neumond** [comment]
I works by just putting files correctly. Use link below with zip file for installation.
https://github.com/neumond/blender-md3/releases/download/0.1/blender_md3.zip

**Comment by Pande** [comment]
Hi thanks for the response. That's what I did the first time but I'll try
again and snap a vid if I don't slap myself for missing something obvious 😋

On Nov 24, 2016 6:27 PM, "Vitalik Verhovodov" <notifications@github.com>
wrote:
>
> I works by just putting files correctly. Use link below with zip file for
installation.
>
https://github.com/neumond/blender-md3/releases/download/0.1/blender_md3.zip

**Comment by neumond** [comment]
Yea, original zip was incorrect for new blender. This link is updated version. You need only `io_scene_md3` folder, without readme etc. This zip installs correctly using button "install from file". I've updated download url on wiki page also. Please try and tell whether it worked for you.

**Comment by neumond** [comment]
Closing this. Should work.
