### ISSUE TITLE
Tag rotation direction inverted

### ISSUE THREAD

**Issue by acqu** [neumond/blender-md3#6]
Hi, i experimented a bit with tags and their rotation direction seems to be inverted.

Here a video which explains basically what i try to do: https://www.youtube.com/watch?v=QW1LV1a-AA4

As you can see the tag_mouth in this video rotates around correct axis, but the rotation direction is inverted (up is down, left is right). But when you negate the w component, it rotates nicely. To test this i parented the helmet to the tag_mouth, so it moves along with it, as it is done inside the quake 3 games.

**Comment by neumond** [comment]
Could reproduce. The 3x3 rotation matrix of tag must be stored transposed.

**Comment by acqu** [comment]
Nice, i checked, and everything works. However, it seems the export function got screwed during latest restruct, it is not functional on my end, can you check? It says something like "Syntax error: only named arguments may follow expression.", line 162 in export script.

**Comment by neumond** [comment]
@acqu which version of python?

**Comment by acqu** [comment]
I got 3.4.2

"PYTHON INTERACTIVE CONSOLE 3.4.2 (default, Dec  7 2014, 18:21:18) [MSC v.1800 64 bit (AMD64)]"

**Comment by neumond** [comment]
@acqu try this version
[blender_md3.zip](https://github.com/neumond/blender-md3/files/1146305/blender_md3.zip)

**Comment by acqu** [comment]
I tried with the head.md3 from wolfenstein et and i was able to do an import, and then export that model, works great now 👍 

Tag direction is working too 👍 

Another problem which i think is easy to fix. During import there seems to be multiple vertices on the same place. Maybe this is is a floating point rounding error or something i dont know, so i recommend to do a "remove doubles" after import, cause when you export the model afterwards, then the vertex normals cause bad lightning.

Hopefully this is it from me, by the way, can you recommend any good learning resources for blender and python. I would really like to also be able to do proper Python coding in blender ;D
