### ISSUE TITLE
I can´t import md3

### ISSUE THREAD

**Issue by raul-valadez** [neumond/blender-md3#7]
why can´t I import md3 in blender 2.78c ?

**Comment by neumond** [comment]
@raul-valadez can you describe better? What happens when you try?

**Comment by raul-valadez** [comment]
Hi, sorry, I can´t find the import option, only export appears, where can I find it?

**Comment by neumond** [comment]
Should appear in menu
![g_001](https://user-images.githubusercontent.com/3260024/27997126-4b1af2dc-64fa-11e7-9fa1-602c9c31c2b6.png)

**Comment by raul-valadez** [comment]
No, in my blender 2.78c (64 bits) only appears in export MD3 (+shaders), after enabled addon, on imports doesn`t shows the quake 3 Model (.md3) option, any clue, I download again your addon and reinstalled again, but the same.

**Comment by raul-valadez** [comment]
Hi, sorry I solved, it was an antique addon causing trouble, I uninstalled it and now your`s  is working,, sorry to bore you!

**Comment by neumond** [comment]
You're welcome, feel free to ask in case of troubles

**Comment by raul-valadez** [comment]
Thanks a lot neumond, and thanks for keep alive .md3 with free software (free as in freedom XD).
You rule!!!
