### ISSUE TITLE
Vertices count

### ISSUE THREAD

**Issue by acqu** [neumond/blender-md3#8]
Hello neumond,

i once wrote about this but got no answer. Basically, your script produces new and unneeded vertices.

Example: make a simple cube with all the settings needed, then export, then import again into Blender. You will see the vertex count trippled.

The core problem is, that md3, as well as mdc, for which i wrote a plugin right now, needs each vertex to be mapped exactly once to the uv map.

I wrote a script, as i said above, for the mdc file format. Check this here: https://github.com/acqu/wet-blender-mdc/commit/55cf892135dd2cf8689d8b511fa8c258eea3308e

I hope this helps, and you can integrate this code, cause sometimes i hit a max vertices count with your import/export script, and generally i think this vertex growth is too much and it seems random. Can you explain why you do this? Or if it really matters? Would be interested on your opinion. Cheers.

**Comment by neumond** [comment]
Hello @acqu 

Yes, vertex duplication is kinda by design. Speaking more strictly, it's a requirement of .md3 format: every vertex can have only one texcoord. With cube example, vertices have 3 texcoords for every plane they share. Script has to duplicate vertex coordinates to be able to export texcoords correctly.

When you import, it takes vertices "as is", so you can weld them in blender if you want. _Probably_ I can weld them automatically on import. Need to take a look here.

Regarding max vertices, it's merely a warning, since the specification defines some limits. If your game engine supports more vertices - just feel free to overcome these limits.

**Comment by acqu** [comment]
> Yes, vertex duplication is kinda by design.

Yes i know. Well, i am still kinda in development phase of this mdc stuff, but it is basically compressed .md3 and so i think i am able to judge .md3 as well. Before doing this i had no idea that both formats only support 1:1 mapping of vertex to uvmap. When i noticed this some days ago, i was able to write some code for it, which checks each vert and how often it is mapped to the uvmap. Doing this, i am able to reduce vertex count significantly.

Example: i have a simple cube with a nice uvmap (standard T-shape, see attachment if you want). Cube has 8 vertices. After export and import with mdc i have 14 verts. The current implementation of the .md3 script has 24 verts. Check attachment:

[test2.zip](https://github.com/neumond/blender-md3/files/1288734/test2.zip)

I got still some problems with uvmap when i import more complex models. I have no idea where it comes from, but on simple models everything works.

So the issue might be fixed by this here:

`   
         def readUVMap(mesh, blenderObject):
        bpy.ops.object.mode_set(mode='OBJECT')
        uvLayer = mesh.uv_layers.active

        if uvLayer == None:
            return None

        if len(mesh.uv_layers) > 1:
            print("MDCExport Info: multiple uv layers found, using active layer.")

        uvMap = []
        uvMapQueue = []
        newVertexCount = 0

        for i in range(0, len(mesh.vertices)):
            uvMap.append(None)
            uvMapQueue.append(None)

        # prepare uvMapQueue
        # this is to handle 1 to many mappings of a vertex to the uvMap
        for polygon in mesh.polygons:

            faceNum = polygon.index

            for loopIndex in polygon.loop_indices:

                loop = mesh.loops[loopIndex]

                vertexIndex = loop.vertex_index
                uvCoordinates = uvLayer.data[loop.index].uv

                if uvMapQueue[vertexIndex] == None:
                    uvMapQueue[vertexIndex] = []

                uvMapQueue[vertexIndex].append((faceNum, uvCoordinates))


        for vertexIndex, vertexMappings in enumerate(uvMapQueue):

            # split vertex by different uv mapping
            splitQueue = []

            for mapping in vertexMappings:

                faceNum = mapping[0]
                uvCoords = mapping[1]

                if uvMap[vertexIndex] == None:

                    uvMap[vertexIndex] = uvCoords

                else:

                    if uvMap[vertexIndex] != uvCoords:
                        splitQueue.append(mapping)

            # process splitQueue, create new verts and faces if needed
            originalUvMapLen = len(uvMap) - 1

            for splitQueueItem in splitQueue:

                uvCoords = splitQueueItem[1]

                # find out if we need to create a new vertex

                j = len(uvMap) - 1
                uvMapIndex = vertexIndex
                uvMapIndexFound = False

                while originalUvMapLen < j:

                    if uvMap[j] == uvCoords:

                        if uvMapIndexFound == True:
                            print("Multiple uv indexes, this shouldn't happen.")

                        uvMapIndexFound = True
                        uvMapIndex = j

                    j -= 1

                # modify verts and normals (simply append)
                if uvMapIndexFound == False:

                    uvMap.append(uvCoords)
                    uvMapIndex = len(uvMap) - 1
                    newVertexCount += 1

                    for frameNum in range(0, len(blenderObject.verts)):

                        frameVert = blenderObject.verts[frameNum][vertexIndex]
                        frameNormal = blenderObject.normals[frameNum][vertexIndex]

                        blenderObject.verts[frameNum].append(frameVert)
                        blenderObject.normals[frameNum].append(frameNormal)

                # modify face indexes to match new vertex
                faceNum = splitQueueItem[0]
                face = blenderObject.faces[faceNum]
                oldVertexNum = vertexIndex
                newVertexNum = uvMapIndex

                if face[0] == oldVertexNum:
                    newFace = (newVertexNum, face[1], face[2])
                    blenderObject.faces[faceNum] = newFace
                elif face[1] == oldVertexNum:
                    newFace = (face[0], newVertexNum, face[2])
                    blenderObject.faces[faceNum] = newFace
                else:
                    newFace = (face[0], face[1], newVertexNum)
                    blenderObject.faces[faceNum] = newFace

        if newVertexCount > 0:
            print("MDCExport Info: new vertices added to output .mdc for object: '" \
                  + str(blenderObject.name) + \
                  "', count=" + str(newVertexCount))

    return uvMap`

But this is only working in my script, cause there are some dependencies to blenderobject. Not sure if you can integrate it or not. I might be able to do a pull request next days.

**Comment by neumond** [comment]
Unique key for vertex currently is (position, normal, texcoords)
https://github.com/neumond/blender-md3/blob/master/io_scene_md3/export_md3.py#L73
It should split vertices correctly now, for any combination of parameters.

**Comment by acqu** [comment]
So i checked now repeatedly and it does not work on models with certain uv maps.

Check the test3.zip here:
[test4.zip](https://github.com/neumond/blender-md3/files/1289978/test4.zip)

This model is set to smooth shading, and the uv map has a t-shape. Export with md3 export option, then import again. No vertices will be duplicated, and all uv map coords will be set to 0.

The result should be a total of 14 vertices and the same uv map.

I am only able to provide very smelly code and it needs to get tested even more (have done already alot), but it seems it works now. Check this function here called readUVMap to see how i do it in mdc.
https://github.com/acqu/wet-blender-mdc/blob/fb4b12238934dfd1bbe8032b0c824502bf4797d1/io_scene_mdc/mdc_modules/blender_scene.py#L51

Note: when you set this cube from above to flat shading, it will correctly export the uv map, and vertices will also be correctly exported.

**Comment by neumond** [comment]
Give me some time, too busy with other things.

**Comment by acqu** [comment]
Ok, no problem. Glad you replied and keep this updated :)

**Comment by neumond** [comment]
> test3.zip
I don't see any UV map generated for the model. You have to create it first, then export as md3.

**Comment by neumond** [comment]
> test4.zip

Don't forget to active UVMap in your material.
![screenshot 2017-09-22 18 05 39](https://user-images.githubusercontent.com/3260024/30752653-9fb9d456-9fc5-11e7-84cc-44c418274b9b.png)

**Comment by neumond** [comment]
I also had problem with revealing imported UVMap: don't forget to select proper scene after switching to UV Editing mode. The mesh after export-import process is auto-triangulated:
![screenshot 2017-09-22 18 44 04](https://user-images.githubusercontent.com/3260024/30752828-27fc2c10-9fc6-11e7-92d4-109ae9a8d90f.png)

**Comment by acqu** [comment]
Ah, the missing UV mapping confused me. It worked before with flat shading enabled. Smooth shading and flat shading are implicit, i kinda wished it was explicit in some kind of export menu. Well. Thanks and it now works.

**Comment by neumond** [comment]
Yea, smooth and flat shadings are exactly as in blender scene. You can export mixed flat/smooth models, e.g. some rounded corner geometry with sharp edges and smooth spherical surfaces. This would be impossible in case of export menu option control.

**Comment by acqu** [comment]
I see. Thanks for taking the time.
